- hosts: Controller
  gather_facts: false
  become: true
  tasks: 
    - copy: 
        src: opt-michman/
        dest: /opt/michman
        owner: root
        group: root
    - copy:
        src: opt-vault/
        dest: /opt/vault
        owner: root
        group: root
    - file:
        path: /etc/vault
        state: directory
        owner: root
        group: root
    - copy:
        src: puppet-modules/vault
        dest: /etc/puppet/modules
        owner: root
        group: root
    - copy:
        src: puppet-modules/michman
        dest: /etc/puppet/modules
        owner: root
        group: root
