- hosts: Controller
  gather_facts: false
  become: true
  tasks: 
    - file:
        path: /etc/vault
        state: directory
        owner: root
        group: root
    - copy:
        src: puppet-modules/vault
        dest: /etc/puppet/modules
        owner: root
        group: root
    - copy:
        src: puppet-modules/michman
        dest: /etc/puppet/modules
        owner: root
        group: root
    - copy:
        src: puppet-modules/horizon
        dest: /usr/share/openstack-puppet/modules
        owner: root
        group: root
    - copy:
        src: puppet-modules/tripleo
        dest: /usr/share/openstack-puppet/modules
        owner: root
        group: root
