#!/bin/bash
set -m

export VAULT_TOKEN=`cat /etc/vault/file/root_token`
export VAULT_ADDR=http://localhost:8200

SECRETS=`vault secrets list  | grep $VAULT_PREFIX`

if [[ "$SECRETS" == "" ]]; then
    vault secrets enable -path=$VAULT_PREFIX kv
fi

vault write $VAULT_PREFIX/$MICHMAN_SSH_PATH pem_key=@/var/lib/kolla/config_files/src/etc/michman/configs/ssh_key
vault write $VAULT_PREFIX/$MICHMAN_MYSQL_PATH @/var/lib/kolla/config_files/src/etc/michman/configs/mariadb_data.json
vault write $VAULT_PREFIX/$MICHMAN_OS_PATH @/var/lib/kolla/config_files/src/etc/michman/configs/openstack_data.json

MICHMAN_TOKEN_LINE=`cat /var/lib/kolla/config_files/src/etc/michman/config.yaml | grep token`
MICHMAN_TOKEN=`cat /var/lib/kolla/config_files/src/etc/michman/config.yaml | grep token | sed "s/token: //"`

if  [[ "$MICHMAN_TOKEN" == "" ]]; then
    sed -i "/token:/d" /var/lib/kolla/config_files/src/etc/michman/config.yaml
    echo "token: $VAULT_TOKEN" >>/var/lib/kolla/config_files/src/etc/michman/config.yaml
fi

SQL_HOST=`vault kv get --field=address michman/mysql | sed "s/:.*//"`
SQL_PORT=`vault kv get --field=address michman/mysql | sed "s/.*://"`
SQL_PASS=`vault kv get --field=password michman/mysql`
SQL_USER=`vault kv get --field=user michman/mysql`
SQL_DATABASE=`vault kv get --field=database michman/mysql`

mysql --host=$SQL_HOST --port=$SQL_PORT --password=$SQL_PASS --user=$SQL_USER $SQL_DATABASE </var/lib/kolla/config_files/src/etc/michman/configs/create_tables.sql
